package importer

import (
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"strings"
	"testing"
	"time"
)

// jira_csv_updated_test.go — the guards behind jira_csv_updated.go.
//
// The package's two-rule shape, for the reason #72 established and #82's C10 re-proved: rule 1
// reads the SHIPPED SOURCE, so a claim about the code cannot rot into decoration; rule 2 pins the
// MEASURED bytes BY HAND, because a source-derived rule CANNOT SEE A DELETION — delete the thing it
// parses and the parse and the code move together, leaving it green.
//
// Provenance for every literal below: scripts/w34-jira-csv-updated-probe.py, run 2026-08-10 against
// jira.atlassian.com's anonymous issue-navigator "csv-all-fields" export, negative-controlled first
// (fabricated host ⇒ URLError · fabricated view ⇒ 400 text/html · fabricated project ⇒ 400
// text/html). 200 issues ordered BY KEY, 402 columns, exactly one "Updated".

// ─── rule 1: the source claims ─────────────────────────────────────────────
//
// jira_csv_updated.go's header says it reuses parseJiraCSVTime "rather than pinning a second layout
// list". Two copies drift, and a second copy would lend this column provenance the FIRST
// measurement gathered for other columns — #75's overclaim, which this package has committed once
// and refused three times now.
//
// ⚠ THIS RULE IS AN ABSENCE ASSERTION AND AN ABSENCE IS GREEN ON A DELETED BODY — #82's C11. So it
// is PAIRED with a floor that asserts a ONE: the file must actually CALL parseJiraCSVTime. A rule
// that asserts a zero needs a companion that asserts a one.
func TestJiraCSVUpdated_Rule1_PinsNoLayoutOfItsOwn(t *testing.T) {
	src, err := os.ReadFile("jira_csv_updated.go")
	if err != nil {
		t.Fatalf("read the shipped source: %v", err)
	}
	// The absence half: no date layout literal of its own. A Go reference layout is recognisable by
	// the reference clock's own numbers; "2006" is the one no other token can be confused with.
	body := stripComments(t, string(src))
	if strings.Contains(body, "2006") {
		t.Errorf("jira_csv_updated.go pins a date layout of its own.\n" +
			"It must reuse parseJiraCSVTime — a second copy drifts from the first and borrows a " +
			"measurement it never made.")
	}
	// The floor half: it must CALL the shared parser. Without this, deleting the function body
	// leaves the absence assertion above perfectly green.
	if !strings.Contains(body, "parseJiraCSVTime") {
		t.Errorf("jira_csv_updated.go never calls parseJiraCSVTime — the absence rule above is " +
			"then satisfied by a file that parses nothing at all")
	}
}

// stripComments removes comments so a rule about CODE cannot be satisfied or broken by prose. The
// header of jira_csv_updated.go quotes measured byte strings, and without this the "2006" check
// would fire on documentation.
func stripComments(t *testing.T, src string) string {
	t.Helper()
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "jira_csv_updated.go", src, 0) // 0 = drop comments
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	var b strings.Builder
	ast.Inspect(f, func(n ast.Node) bool {
		if lit, ok := n.(*ast.BasicLit); ok {
			b.WriteString(lit.Value)
			b.WriteString("\n")
		}
		if id, ok := n.(*ast.Ident); ok {
			b.WriteString(id.Name)
			b.WriteString("\n")
		}
		return true
	})
	return b.String()
}

// TestJiraCSVUpdated_Rule1_TheMapperIsWiredIntoJiraRowMapper — a mapper nothing calls is a mapper
// that cannot fail. #83's equivalent guard exists because this package once shipped a field whose
// unit tests were green and whose call site did not exist.
func TestJiraCSVUpdated_Rule1_TheMapperIsWiredIntoJiraRowMapper(t *testing.T) {
	src, err := os.ReadFile("csv.go")
	if err != nil {
		t.Fatalf("read csv.go: %v", err)
	}
	body := stripCommentsOf(t, "csv.go", string(src))
	if !strings.Contains(body, "jiraCSVUpdated") {
		t.Fatalf("csv.go never calls jiraCSVUpdated — the column is measured, mapped, unit-tested " +
			"and never read")
	}
	if !strings.Contains(body, "UpdatedAt") {
		t.Errorf("csv.go never assigns UpdatedAt — the mapper can be called and its result dropped")
	}
}

func stripCommentsOf(t *testing.T, name, src string) string {
	t.Helper()
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, name, src, 0)
	if err != nil {
		t.Fatalf("parse %s: %v", name, err)
	}
	var b strings.Builder
	ast.Inspect(f, func(n ast.Node) bool {
		if id, ok := n.(*ast.Ident); ok {
			b.WriteString(id.Name)
			b.WriteString("\n")
		}
		return true
	})
	return b.String()
}

// ─── rule 2: the measured bytes, pinned by hand ────────────────────────────
//
// These three strings are transcribed from the probe run, NOT generated by formatting a constant
// with itself (#75's C6). If the shipped layout list stops accepting a real Jira's rendering, this
// fails — which a source-derived rule cannot do.
func TestJiraCSVUpdated_Rule2_TheMeasuredBytes(t *testing.T) {
	measured := []struct {
		raw  string
		want time.Time
	}{
		{"03/Mar/2025 9:09 AM", time.Date(2025, 3, 3, 9, 9, 0, 0, time.UTC)},
		{"27/Mar/2019 11:41 PM", time.Date(2019, 3, 27, 23, 41, 0, 0, time.UTC)},
		{"10/Aug/2026 12:32 AM", time.Date(2026, 8, 10, 0, 32, 0, 0, time.UTC)},
	}
	for _, m := range measured {
		got, ok := parseJiraCSVTime(m.raw)
		if !ok {
			t.Errorf("a real Jira's Updated value %q is not accepted by any pinned layout", m.raw)
			continue
		}
		if !got.Equal(m.want) {
			t.Errorf("parseJiraCSVTime(%q) = %s, want %s", m.raw, got, m.want)
		}
	}
}

// TestJiraCSVUpdated_TheColumnSpellingIsPinned — the header string, by hand. The probe measured
// exactly one "Updated" column; a rename in the constant must fail here rather than silently make
// every import fall down the no-column branch.
func TestJiraCSVUpdated_TheColumnSpellingIsPinned(t *testing.T) {
	if jiraCSVUpdatedColumn != "Updated" {
		t.Errorf("jiraCSVUpdatedColumn = %q, want %q — the spelling measured on a real export",
			jiraCSVUpdatedColumn, "Updated")
	}
}

// ─── the four outcomes ─────────────────────────────────────────────────────
func TestJiraCSVUpdated_TheFourOutcomes(t *testing.T) {
	t.Run("a value the layouts accept lands and says nothing", func(t *testing.T) {
		ci, row := buildIndex([]string{"Summary", "Updated"}), []string{"a", "03/Mar/2025 9:09 AM"}
		got, notes := jiraCSVUpdated(ci, row)
		if len(notes) != 0 {
			t.Errorf("notes = %+v, want none", notes)
		}
		if want := time.Date(2025, 3, 3, 9, 9, 0, 0, time.UTC); !got.Equal(want) {
			t.Errorf("got %s, want %s", got, want)
		}
	})

	t.Run("no Updated column at all is its own report", func(t *testing.T) {
		ci, row := buildIndex([]string{"Summary", "Status"}), []string{"a", "Open"}
		got, notes := jiraCSVUpdated(ci, row)
		if !got.IsZero() {
			t.Errorf("got %s, want the zero time", got)
		}
		if len(notes) != 1 || notes[0].Via != viaNoUpdatedColumn {
			t.Fatalf("notes = %+v, want exactly one %s", notes, viaNoUpdatedColumn)
		}
	})

	t.Run("an empty cell under a present header is a different report", func(t *testing.T) {
		ci, row := buildIndex([]string{"Summary", "Updated"}), []string{"a", ""}
		_, notes := jiraCSVUpdated(ci, row)
		if len(notes) != 1 || notes[0].Via != viaNoUpdatedValue {
			t.Fatalf("notes = %+v, want exactly one %s", notes, viaNoUpdatedValue)
		}
	})

	t.Run("a shape no pinned layout accepts is REPORTED, never defaulted", func(t *testing.T) {
		ci, row := buildIndex([]string{"Summary", "Updated"}), []string{"a", "2025-03-03T09:09:00Z"}
		got, notes := jiraCSVUpdated(ci, row)
		if !got.IsZero() {
			t.Errorf("got %s, want the zero time — an unparseable value must not become a guess", got)
		}
		if len(notes) != 1 || notes[0].Via != viaUnparseableDate {
			t.Fatalf("notes = %+v, want exactly one %s", notes, viaUnparseableDate)
		}
		if notes[0].Value != "2025-03-03T09:09:00Z" {
			t.Errorf("the note drops the provider's value; got %q", notes[0].Value)
		}
	})
}

// TestJiraCSVUpdated_TheTwoAbsencesRenderDifferently — the whole reason the two Via constants are
// kept apart. If they rendered the same sentence an operator could not tell "this export has no
// Updated column" from "these rows had empty cells", and #73's structural-zero defence would be
// decoration.
func TestJiraCSVUpdated_TheTwoAbsencesRenderDifferently(t *testing.T) {
	noColumn := FieldNote{Field: fieldUpdated, Via: viaNoUpdatedColumn}.render(3)
	noValue := FieldNote{Field: fieldUpdated, Via: viaNoUpdatedValue}.render(3)
	if noColumn == noValue {
		t.Fatalf("both absences render the same sentence: %q", noColumn)
	}
	for _, s := range []string{noColumn, noValue} {
		if strings.TrimSpace(s) == "" {
			t.Fatalf("an absence rendered as the empty string — it would vanish from the report")
		}
	}
	// The no-column sentence must name the column, so the operator knows what to re-export.
	if !strings.Contains(noColumn, jiraCSVUpdatedColumn) {
		t.Errorf("the no-column sentence does not name %q: %q", jiraCSVUpdatedColumn, noColumn)
	}
}
